name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn
      - name: Test
        uses: ianwalter/puppeteer@v2.0.0
        env:
          CI: true
        with:
          args: ./test-ci.sh
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: image_snapshots
          path: ./src/__image_snapshots__